# Generated by Django 6.0.1 on 2026-03-11 20:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TERMO_USO', 'Termos de Uso'), ('POLITICA_PRIVACIDADE', 'Política de Privacidade')], max_length=50)),
                ('versao', models.CharField(help_text='Ex: 1.0, 1.1, 2.0', max_length=20)),
                ('conteudo', models.TextField(help_text='Conteúdo HTML do documento')),
                ('is_active', models.BooleanField(default=False, help_text='Apenas um documento por tipo pode estar ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Documento Legal',
                'verbose_name_plural': 'Documentos Legais',
                'ordering': ['-data_publicacao'],
                'unique_together': {('tipo', 'versao')},
            },
        ),
        migrations.CreateModel(
            name='AceiteDocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceites_legais', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceites', to='legal.documentolegal')),
            ],
            options={
                'verbose_name': 'Aceite de Documento Legal',
                'verbose_name_plural': 'Aceites de Documentos Legais',
                'ordering': ['-data_hora'],
                'unique_together': {('user', 'documento')},
            },
        ),
    ]
