# Generated by Django 6.0.1 on 2026-03-11 21:40

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentolegal',
            name='conteudo',
            field=tinymce.models.HTMLField(help_text='Conteúdo HTML do documento'),
        ),
    ]
