# Generated by Django 6.0.1 on 2026-02-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parecer',
            name='autuacao_pdf_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='consolidado_pdf_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='data_protocolo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='data_sessao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='pa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='prazo_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='recorrente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='sgpe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='status_fase',
            field=models.IntegerField(default=1),
        ),
    ]
