# Generated by Django 6.0.1 on 2026-02-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_parecer_is_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='parecer',
            name='nota_blindagem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='parecer_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='tese',
            field=models.TextField(blank=True, null=True),
        ),
    ]
