# Generated by Django 6.0.2 on 2026-02-23 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_parecer_paginas_defesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoParecer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Logo em PNG', upload_to='assets/logos/')),
                ('titulo_cabecalho', models.CharField(default='P-JARI/SC', max_length=255)),
                ('subtitulo_cabecalho', models.CharField(blank=True, max_length=255)),
                ('rodape_deferido', models.TextField(help_text='HTML para caso de Deferimento')),
                ('rodape_indeferido', models.TextField(help_text='HTML para caso de Indeferimento')),
            ],
            options={
                'verbose_name': 'Configuração do Parecer',
                'verbose_name_plural': 'Configurações do Parecer',
            },
        ),
        migrations.CreateModel(
            name='ParecerFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_html', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status_resultado', models.CharField(max_length=20)),
                ('parecer_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pareceres_finais', to='chat.parecer')),
            ],
        ),
    ]
