# Generated by Django 6.0.2 on 2026-02-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_configuracaoparecer_parecerfinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoparecer',
            name='subtitulo_cabecalho',
            field=models.TextField(blank=True, default='JUNTA ADMINISTRATIVA DE RECURSOS DE INFRAÇÃO –\nJARI REGIONAL DE CHAPECÓ'),
        ),
        migrations.AlterField(
            model_name='configuracaoparecer',
            name='titulo_cabecalho',
            field=models.TextField(default='ESTADO DE SANTA CATARINA\nDEPARTAMENTO ESTADUAL DE TRÂNSITO'),
        ),
    ]
