# Generated by Django 6.0.1 on 2026-02-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='viu_boas_vindas',
            field=models.BooleanField(default=False),
        ),
    ]
