# Generated by Django 6.0.1 on 2026-02-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_userprofile_viu_boas_vindas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='credits',
            field=models.IntegerField(default=2),
        ),
    ]
