# Generated by Django 6.0.1 on 2026-02-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_userprofile_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='parecer',
            name='admissibilidade_texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='analise_tese_texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
