# Generated by Django 6.0.1 on 2026-02-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_parecer_admissibilidade_texto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parecer',
            name='nota_blindagem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
