# Generated by Django 6.0.1 on 2026-02-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_parecer_nota_blindagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='parecer',
            name='dossie_fontes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
