# Generated by Django 6.0.1 on 2026-03-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_parecer_perplexity_result_parecer_vertex_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='PjariCacheConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Se desativado, o sistema sempre fará buscas externas na Fase 4 e 5.', verbose_name='Ativar PJARI-CACHE')),
                ('total_requests', models.IntegerField(default=0, verbose_name='Total de Consultas')),
                ('total_hits', models.IntegerField(default=0, verbose_name='Total de Hits (Acertos no Cache)')),
            ],
            options={
                'verbose_name': 'PJARI-CACHE: Configuração e Métricas',
                'verbose_name_plural': 'PJARI-CACHE: Configurações',
            },
        ),
        migrations.CreateModel(
            name='PjariCacheEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True, verbose_name='Chave de Cache (Artigo + Núcleo)')),
                ('vertex_result', models.TextField(verbose_name='Resultado Vertex (Fundamentação)')),
                ('perplexity_result', models.TextField(verbose_name='Resultado Perplexity (Jurisprudência)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('hit_count', models.IntegerField(default=0, verbose_name='Vezes Utilizadas')),
            ],
            options={
                'verbose_name': 'PJARI-CACHE: Memória Armazenada',
                'verbose_name_plural': 'PJARI-CACHE: Memórias Armazenadas',
                'ordering': ['-created_at'],
            },
        ),
    ]
