# Generated by Django 6.0.1 on 2026-03-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_pjaricacheconfig_pjaricacheentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='parecer',
            name='blindagem_detalhes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='blindagem_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='has_decadencia',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='has_prescricao_intercorrente',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='has_prescricao_punitiva',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='is_tempestivo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='tabela_datas_sensiveis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
