# Generated by Django 6.0.1 on 2026-03-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_parecer_blindagem_detalhes_parecer_blindagem_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta',
            name='posicao',
            field=models.IntegerField(default=0),
        ),
    ]
