# Generated by Django 6.0.1 on 2026-03-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_userprofile_can_view_global_stats_airequestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='parecer',
            name='tempo_julgamento_segundos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
