# Generated by Django 6.0.1 on 2026-03-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_bancotese'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancotese',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bancotese',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
    ]
