# Generated by Django 6.0.1 on 2026-03-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_bancotese_is_public_bancotese_usage_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='credits',
            field=models.IntegerField(default=5),
        ),
    ]
