# Generated by Django 6.0.1 on 2026-03-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_postforum_comentarioforum'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ultimo_acesso_forum',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
