# Generated by Django 6.0.1 on 2026-03-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_userprofile_ultimo_acesso_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='postforum',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='forum_images/'),
        ),
    ]
