# Generated by Django 6.0.1 on 2026-03-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_postforum_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_seen_tour',
            field=models.BooleanField(default=False),
        ),
    ]
