# Generated by Django 6.0.1 on 2026-03-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0030_termoaceitelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequestlog',
            name='is_miss',
            field=models.BooleanField(default=False, help_text='Se True, significa que a IA não retornou resultados práticos (Ex: RAG vazio)'),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='query_text',
            field=models.TextField(blank=True, help_text='Termo pesquisado, caso aplicável (Ex: Vertex RAG query)', null=True),
        ),
    ]
