# Generated by Django 6.0.1 on 2026-03-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0031_airequestlog_is_miss_airequestlog_query_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequestlog',
            name='is_pdf_defect',
            field=models.BooleanField(default=False, help_text='Se True, significa que o OCR do PDF falhou e a IA não conseguiu ler o conteúdo'),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='latency_ms',
            field=models.IntegerField(default=0, help_text='Tempo de execução da chamada em milissegundos'),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='model_name',
            field=models.CharField(blank=True, help_text='Versão do modelo (ex: sonar-pro, gemini-2.5-flash)', max_length=100, null=True),
        ),
    ]
