# Generated by Django 6.0.1 on 2026-03-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0032_airequestlog_is_pdf_defect_airequestlog_latency_ms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PjariVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.IntegerField(default=1, verbose_name='Major (Paradigma)')),
                ('minor', models.IntegerField(default=2, verbose_name='Minor (Raciocínio/Lógica)')),
                ('patch', models.IntegerField(default=0, verbose_name='Patch/Versão Vertex (Base de Leis)')),
                ('logica_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash do logica_jari.md')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Controle de Versão (JARI)',
                'verbose_name_plural': 'Controle de Versão (JARI)',
            },
        ),
    ]
