# Generated by Django 6.0.1 on 2026-03-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0033_pjariversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateTimeField(auto_now_add=True)),
                ('status_operacional', models.BooleanField(default=True)),
                ('latencia_media_apis', models.FloatField(default=0.0)),
                ('math_score', models.CharField(default='N/A', max_length=50)),
                ('tempo_total_ciclo', models.FloatField(default=0.0)),
                ('log_detalhado', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-data_execucao'],
            },
        ),
    ]
