# Generated by Django 6.0.1 on 2026-03-16 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0034_systemhealthcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parecer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='chat.parecer')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
