# Generated by Django 6.0.1 on 2026-03-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0035_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='parecer',
            name='ata_pdf_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
