# Generated by Django 6.0.1 on 2026-03-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0036_parecer_ata_pdf_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaoparecer',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='configuracaoparecer',
            name='subtitulo_cabecalho',
        ),
        migrations.RemoveField(
            model_name='configuracaoparecer',
            name='titulo_cabecalho',
        ),
        migrations.AddField(
            model_name='configuracaoparecer',
            name='cabecalho_imagem',
            field=models.ImageField(blank=True, help_text='Faça o upload do banner completo em arquivo de imagem PNG ou JPG. Recomendado conter o texto e logos nas extremidades com proporção wide (painel).', null=True, upload_to='assets/logos/'),
        ),
    ]
