# Generated by Django 6.0.1 on 2026-03-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0037_remove_configuracaoparecer_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parecer',
            name='feedback_notes',
            field=models.TextField(blank=True, help_text='Comentário livre do usuário sobre o que faltou na IA', null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='feedback_score',
            field=models.IntegerField(blank=True, help_text='Nota de 0 a 100 dada pelo usuário sobre o parecer gerado', null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='feedback_tags',
            field=models.CharField(blank=True, help_text='Tags de erro pontuadas (ex: erro-de-data, erro-jurisprudencia)', max_length=500, null=True),
        ),
    ]
