# Generated by Django 6.0.1 on 2026-03-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0039_alter_parecer_pdf_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executado_em', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('passou', models.IntegerField(default=0)),
                ('falhou', models.IntegerField(default=0)),
                ('duracao_ms', models.IntegerField(default=0)),
                ('detalhes_json', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-executado_em'],
            },
        ),
    ]
