# Generated by Django 6.0.1 on 2026-03-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0040_add_testrun_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='parecer',
            name='julgador_decadencia',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='julgador_prescricao_intercorrente',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='julgador_prescricao_punitiva',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='julgador_tempestivo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
