# Generated by Django 6.0.1 on 2026-03-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0044_parecer_fase1_extracao_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='parecer',
            name='checklist_auditoria_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parecer',
            name='data_infracao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
