# Generated by Django 6.0.1 on 2026-03-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0045_add_data_infracao_checklist_auditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parecer',
            name='is_saved',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='parecer',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
