# Generated by Django 6.0.1 on 2026-03-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0046_add_db_indexes_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='parecer',
            name='data_totalizacao_pontos',
            field=models.DateField(blank=True, null=True),
        ),
    ]
