# Generated by Django 6.0.1 on 2026-05-03 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0052_parecer_created_at_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='chat_audite_evento_c64710_idx',
            old_name='audit_evento_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='chat_audite_user_id_8fa3db_idx',
            old_name='audit_user_ts_idx',
        ),
        migrations.AlterField(
            model_name='parecer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='airequestlog',
            index=models.Index(fields=['-data_requisicao'], name='chat_airequ_data_re_675e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='airequestlog',
            index=models.Index(fields=['provider', '-data_requisicao'], name='chat_airequ_provide_3ef01b_idx'),
        ),
    ]
