# Generated by Django 6.0.1 on 2026-05-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0053_add_airequestlog_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='parecer',
            name='resultado_final',
            field=models.CharField(blank=True, db_index=True, help_text='DEFERIDO ou INDEFERIDO — derivado de parecer_final no save()', max_length=15, null=True),
        ),
    ]
