# Generated by Django 6.0.4 on 2026-05-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0055_populate_resultado_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='parecer',
            name='fase5_provider',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
