# Generated by Django 6.0.4 on 2026-05-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0056_add_fase5_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='pjaricacheentry',
            name='pacote_compilado',
            field=models.TextField(blank=True, null=True, verbose_name='Pacote Normativo Pré-digerido'),
        ),
        migrations.AddField(
            model_name='pjaricacheentry',
            name='tipo_infracao',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Tipo de Infração Normalizado'),
        ),
        migrations.AddField(
            model_name='pjaricacheentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
    ]
