# Generated by Django 6.0.4 on 2026-05-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0058_pgvector_documento_normativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_padrao', models.CharField(choices=[('atual', 'Atual (Flash + Haiku)'), ('reforcado', 'Reforçado (Pro F5 + Sonnet F4/F6)'), ('maximo', 'Máximo (Pro + Sonnet em todas as fases)')], default='atual', help_text='Nível aplicado a todos os usuários que não possuem override individual.', max_length=20, verbose_name='Nível padrão de IA')),
            ],
            options={
                'verbose_name': 'Nível de IA (Global)',
                'verbose_name_plural': 'Nível de IA (Global)',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(blank=True, choices=[('', 'Usar padrão global'), ('atual', 'Atual (Flash + Haiku)'), ('reforcado', 'Reforçado (Pro F5 + Sonnet F4/F6)'), ('maximo', 'Máximo (Pro + Sonnet em todas as fases)')], default='', help_text='Override individual. Deixe vazio para usar o nível global.', max_length=20, verbose_name='Nível de IA'),
        ),
        migrations.AlterField(
            model_name='documentonormativo',
            name='embedding',
            field=models.JSONField(default=list, help_text='Vetor de embedding (sentence-transformers)'),
        ),
    ]
