# Generated by Django 6.0.4 on 2026-05-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0059_tier_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parecer',
            name='pa',
        ),
        migrations.RemoveField(
            model_name='parecer',
            name='sgpe',
        ),
    ]
