# Generated by Django 6.0.4 on 2026-05-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0060_remove_pa_sgpe_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='parecer',
            name='has_prescricao_intercorrente_bienal',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
