# Generated by Django 6.0.4 on 2026-05-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0061_add_prescricao_intercorrente_bienal'),
    ]

    operations = [
        migrations.AddField(
            model_name='parecer',
            name='julgador_prescricao_intercorrente_bienal',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
