"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.redis import RedisIntegration
from sentry_sdk.integrations.logging import LoggingIntegration
import logging as _logging

def _sentry_before_send(event, hint):
    """Filtra e enriquece eventos antes de enviar ao Sentry."""
    # Remove erros 404 e 403 — não são bugs do sistema
    if "exc_info" in hint:
        exc_type, _, _ = hint["exc_info"]
        try:
            from django.http import Http404
            from django.core.exceptions import PermissionDenied
            if exc_type in (Http404, PermissionDenied):
                return None
        except ImportError:
            pass
    return event


sentry_dsn = os.environ.get('SENTRY_DSN')
_is_debug = os.environ.get('DEBUG', 'False') == 'True'

if sentry_dsn:
    sentry_sdk.init(
        dsn=sentry_dsn,
        environment="development" if _is_debug else "production",
        release=os.environ.get('GIT_COMMIT', 'unknown'),

        integrations=[
            DjangoIntegration(
                transaction_style="url",      # agrupa por rota, não por view
                http_methods_to_capture=("GET", "POST", "PUT", "PATCH", "DELETE"),
            ),
            CeleryIntegration(
                monitor_beat_tasks=True,      # monitora rodar_testes_engine_task via Cron Monitor
                propagate_traces=True,        # rastreia tarefa pai→filho
            ),
            RedisIntegration(),
            LoggingIntegration(
                level=_logging.WARNING,       # captura WARNING+ como breadcrumbs
                event_level=_logging.ERROR,   # envia ao Sentry apenas ERROR+
            ),
        ],

        # Performance — 20% em prod (conserva os 5M spans do plano Team)
        traces_sample_rate=0.0 if _is_debug else 0.2,
        profile_session_sample_rate=0.0 if _is_debug else 0.1,  # profiling: 10%
        profile_lifecycle="trace",

        # Dados pessoais: manter desativado (LGPD)
        send_default_pii=False,

        # Captura variáveis locais nos stack frames (apenas em dev — risco de vazar tokens/dados em prod)
        include_local_variables=_is_debug,

        # Ignora erros operacionais esperados que poluem o painel
        ignore_errors=[
            KeyboardInterrupt,
            SystemExit,
        ],

        # Antes de enviar: filtra 404/403 que poluem o painel
        before_send=_sentry_before_send,
    )
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Diretório dos PDFs normativos para RAG local (pgvector)
NORMATIVO_DIR = os.environ.get('NORMATIVO_DIR', str(BASE_DIR / 'data' / 'normativo'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if os.environ.get('DEBUG', 'False') != 'True':
        raise RuntimeError(
            "SECRET_KEY não definida! Defina a variável de ambiente SECRET_KEY antes de iniciar em produção."
        )
    SECRET_KEY = 'django-insecure-default-key-dev-only'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

allowed_hosts = os.environ.get('ALLOWED_HOSTS')
if allowed_hosts:
    ALLOWED_HOSTS = allowed_hosts.split(',')
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.railway.app', 'pjarisc.com.br', 'www.pjarisc.com.br']

csrf_trusted = os.environ.get('CSRF_TRUSTED_ORIGINS')
if csrf_trusted:
    CSRF_TRUSTED_ORIGINS = csrf_trusted.split(',')
else:
    # Allow Railway and custom domains for CSRF by default
    CSRF_TRUSTED_ORIGINS = []

# Sempre forçar os domínios básicos para evitar erros de deploy vazio (evita 403 CSRF)
_railway_url = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
base_origins = ['https://pjarisc.com.br', 'https://www.pjarisc.com.br']
if _railway_url:
    base_origins.append(f'https://{_railway_url}')
else:
    base_origins.append('https://*.railway.app')  # fallback wildcard se RAILWAY_PUBLIC_DOMAIN não definida
for origin in base_origins:
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)

# Forçar uso do HTTPS para CSRF/Session em ambiente Prod (DEBUG=False)
if not DEBUG:
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SECURE_REDIRECT_EXEMPT = [r'^health/$']  # Railway healthcheck usa HTTP interno
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HSTS (Strict-Transport-Security)
    SECURE_HSTS_SECONDS = 31536000 # 1 ano
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Proteções nativas de navegador
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Permitir sessão através do root e do www
    SESSION_COOKIE_DOMAIN = '.pjarisc.com.br'
    CSRF_COOKIE_DOMAIN = '.pjarisc.com.br'
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'
# Stripe Settings
STRIPE_PUBLIC_KEY = os.environ.get('STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET')

ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL', '')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'anymail',
    'chat',
    'legal',
    'tinymce',

    # Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # Providers
    'allauth.socialaccount.providers.google',
]

# Silk só ativo quando explicitamente ligado via env — nunca auto-ativo em DEBUG
SILK_ENABLED = os.environ.get('SILK_ENABLED', 'False') == 'True'

if SILK_ENABLED:
    INSTALLED_APPS += ['silk']

_SILK_MIDDLEWARE = ['silk.middleware.SilkyMiddleware'] if SILK_ENABLED else []

MIDDLEWARE = _SILK_MIDDLEWARE + [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Allauth middleware
    'allauth.account.middleware.AccountMiddleware',

    # Clerk Auth Middleware — deve rodar ANTES do Terms para que request.user
    # já esteja definido quando o RequireTermsAcceptanceMiddleware verificar.
    'chat.middleware_clerk.ClerkAuthenticationMiddleware',

    # Termos de Uso Middleware
    'chat.middleware.RequireTermsAcceptanceMiddleware',
]

# Permitir Iframes (SplitScreen de PDFs nativo do painel)
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Content-Security-Policy (django-csp)
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net", "https://js.clerk.dev", "https://*.clerk.accounts.dev")
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net", "https://fonts.googleapis.com")
CSP_IMG_SRC = ("'self'", "data:", "https:", "blob:")
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net")
CSP_CONNECT_SRC = ("'self'", "https://*.clerk.dev", "https://*.clerk.accounts.dev", "https://api.clerk.com", "https://*.sentry.io")
CSP_FRAME_SRC = ("'self'", "https://*.railway.app", "https://pjarisc.com.br")
CSP_FRAME_ANCESTORS = ("'self'",)

# django-silk: profiling de requests e queries
if SILK_ENABLED:
    SILKY_PYTHON_PROFILER = True
    SILKY_AUTHENTICATION = True           # exige login para ver /silk/
    SILKY_AUTHORISATION = True            # exige is_staff
    if DEBUG:
        SILKY_MAX_RECORDED_REQUESTS = 1000
        SILKY_INTERCEPT_PERCENT = 100     # captura tudo em dev
    else:
        SILKY_MAX_RECORDED_REQUESTS = 200
        SILKY_INTERCEPT_PERCENT = 5       # captura 5% em produção

ROOT_URLCONF = 'config.urls'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# Allauth settings
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['first_name*', 'email*', 'password1*', 'password2*']
ACCOUNT_SIGNUP_FORM_CLASS = 'chat.adapters.CustomSignupForm'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
SOCIALACCOUNT_ADAPTER = 'chat.adapters.CustomSocialAccountAdapter'

# Redirects de autenticação padrão do Django
LOGIN_URL = '/app/'
LOGIN_REDIRECT_URL = '/app/'
LOGOUT_REDIRECT_URL = '/'

if DEBUG:
    # Envio de e-mail para o terminal (Simulação de envio p/ Dev Local)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Envio real via Resend API (Produção)
    EMAIL_BACKEND = 'anymail.backends.resend.EmailBackend'
    ANYMAIL = {
        'RESEND_API_KEY': os.environ.get('RESEND_API_KEY', ''),
    }
    DEFAULT_FROM_EMAIL = 'validacao@pjarisc.com.br'
    SERVER_EMAIL = 'validacao@pjarisc.com.br'


# Pular a tela intermediária chata do allauth "sign in via..."
SOCIALACCOUNT_LOGIN_ON_GET = True

# Permitir logout com cliques simples em Links e Views cacheadas sem necessitar forms POST + CSRF ativo.
ACCOUNT_LOGOUT_ON_GET = False

# Permite conectar direto e não exige verificação dupla para quem loga com redes sociais
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"

# Clerk SDK Environment Hooks (Cloud or Local)
CLERK_PUBLISHABLE_KEY = os.getenv("CLERK_PUBLISHABLE_KEY", "")
CLERK_SECRET_KEY = os.getenv("CLERK_SECRET_KEY", "")
CLERK_WEBHOOK_SECRET = os.getenv("CLERK_WEBHOOK_SECRET", "")

# Optionally set login redirect to home
LOGIN_REDIRECT_URL = '/app/'

_TEMPLATE_CONTEXT_PROCESSORS = [
    'django.template.context_processors.request',
    'django.contrib.auth.context_processors.auth',
    'django.contrib.messages.context_processors.messages',
    'chat.context_processors.pjari_info',
]

if DEBUG:
    # Dev: APP_DIRS recarrega templates automaticamente ao editar
    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [BASE_DIR / 'templates'],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': _TEMPLATE_CONTEXT_PROCESSORS,
            },
        },
    ]
else:
    # Prod: CachedLoader compila templates uma vez e mantém em memória
    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [BASE_DIR / 'templates'],
            'APP_DIRS': False,
            'OPTIONS': {
                'context_processors': _TEMPLATE_CONTEXT_PROCESSORS,
                'loaders': [
                    ('django.template.loaders.cached.Loader', [
                        'django.template.loaders.filesystem.Loader',
                        'django.template.loaders.app_directories.Loader',
                    ]),
                ],
            },
        },
    ]

PJARI_VERSION = '1.2'
CLARITY_PROJECT_ID = os.environ.get('CLARITY_PROJECT_ID', '')

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        env='DATABASE_URL',
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=60 if DEBUG else 60,
        conn_health_checks=True,
    )
}


# Password hashing — Argon2id como preferido (OWASP recommendation)
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'chat' / 'static',
]

# WhiteNoise: cache de estáticos por 1 ano no browser (hash no nome garante invalidação)
WHITENOISE_MAX_AGE = 31536000  # 1 ano em segundos
WHITENOISE_USE_FINDERS = False
# Storage Configuration
# Prioridade: Railway Bucket (S3) → GCS → FileSystem local
USE_GCS = os.environ.get('USE_GCS', 'False') == 'True'

# Fase 1 texto-only: extrai Markdown estruturado dos PDFs via PyMuPDF e envia
# ao Gemini como texto puro (sem Files API visual). Reduz latência e custo.
# False = modo legado (Files API visual) | True = modo texto-only (Markdown)
FASE1_TEXT_ONLY = os.environ.get('FASE1_TEXT_ONLY', 'True') == 'True'

# Unifica Fases 1+2 numa única chamada Gemini: extrai campos administrativos +
# tabela de datas sensíveis + tipo_penalidade + flagrante de uma vez.
# O julgador vê um único formulário de confirmação em vez de dois sequenciais.
UNIFIED_FASE1_FASE2 = os.environ.get('UNIFIED_FASE1_FASE2', 'True') == 'True'

# Railway Bucket (S3-compatible) — env vars injetadas via "Add to Service" (estilo AWS SDK)
# AWS_ENDPOINT_URL, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_S3_BUCKET_NAME, AWS_DEFAULT_REGION
_s3_endpoint = os.environ.get('AWS_ENDPOINT_URL', '')
_s3_access_key = os.environ.get('AWS_ACCESS_KEY_ID', '')

if _s3_endpoint and _s3_access_key:
    # Railway Bucket (S3-compatible object storage)
    # django-storages lê AWS_ACCESS_KEY_ID e AWS_SECRET_ACCESS_KEY automaticamente
    AWS_S3_ENDPOINT_URL = _s3_endpoint
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_S3_BUCKET_NAME', '')
    AWS_S3_REGION_NAME = os.environ.get('AWS_DEFAULT_REGION', 'auto')
    AWS_S3_ADDRESSING_STYLE = 'virtual'
    AWS_QUERYSTRING_AUTH = True
    from datetime import timedelta
    AWS_QUERYSTRING_EXPIRE = int(timedelta(days=1).total_seconds())

    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        },
        'staticfiles': {
            'BACKEND': 'config.custom_storage.TolerantWhiteNoiseStorage',
        },
    }
elif USE_GCS:
    # Google Cloud Storage (legado — billing precisa estar ativo)
    GS_BUCKET_NAME = os.environ.get('GS_BUCKET_NAME', 'pjari-midias')
    google_creds_env = os.environ.get('GOOGLE_APPLICATION_CREDENTIALS', '')

    if google_creds_env.strip().startswith('{'):
        import json
        from google.oauth2 import service_account
        try:
            creds_info = json.loads(google_creds_env)
            GS_CREDENTIALS = service_account.Credentials.from_service_account_info(creds_info)
            STORAGES = {
                'default': {
                    'BACKEND': 'storages.backends.gcloud.GoogleCloudStorage',
                },
                'staticfiles': {
                    'BACKEND': 'config.custom_storage.TolerantWhiteNoiseStorage',
                },
            }
            GS_QUERYSTRING_AUTH = True
            from datetime import timedelta
            GS_EXPIRATION = timedelta(days=1)
            if 'GOOGLE_APPLICATION_CREDENTIALS' in os.environ:
                del os.environ['GOOGLE_APPLICATION_CREDENTIALS']
        except Exception:
            STORAGES = {
                'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
                'staticfiles': {'BACKEND': 'config.custom_storage.TolerantWhiteNoiseStorage'},
            }
            MEDIA_URL = '/media/'
            MEDIA_ROOT = os.environ.get('MEDIA_ROOT', str(BASE_DIR / 'media'))
    else:
        GS_CREDENTIALS_FILE = google_creds_env or str(BASE_DIR / 'gcp-credentials.json')
        if os.path.exists(GS_CREDENTIALS_FILE):
            if 'GOOGLE_APPLICATION_CREDENTIALS' not in os.environ:
                os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = GS_CREDENTIALS_FILE
            STORAGES = {
                'default': {
                    'BACKEND': 'storages.backends.gcloud.GoogleCloudStorage',
                },
                'staticfiles': {
                    'BACKEND': 'config.custom_storage.TolerantWhiteNoiseStorage',
                },
            }
            GS_QUERYSTRING_AUTH = True
            from datetime import timedelta
            GS_EXPIRATION = timedelta(days=1)
        else:
            STORAGES = {
                'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
                'staticfiles': {'BACKEND': 'config.custom_storage.TolerantWhiteNoiseStorage'},
            }
            MEDIA_URL = '/media/'
            MEDIA_ROOT = os.environ.get('MEDIA_ROOT', str(BASE_DIR / 'media'))
else:
    # Desenvolvimento local — FileSystemStorage
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {'BACKEND': 'config.custom_storage.TolerantWhiteNoiseStorage'},
    }
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.environ.get('MEDIA_ROOT', str(BASE_DIR / 'media'))

LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'

# Celery & Redis Configuration
_redis_url = os.environ.get('REDIS_PRIVATE_URL') or os.environ.get('REDIS_URL', 'redis://localhost:6379/0')

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': _redis_url,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 2,
            'SOCKET_TIMEOUT': 2,
            'SOCKET_KEEPALIVE': True,
            'RETRY_ON_TIMEOUT': True,
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 100,
                'socket_keepalive': True,
                'socket_keepalive_options': {},
            },
            'IGNORE_EXCEPTIONS': True,  # Não quebra a request se Redis cair
        },
        'KEY_PREFIX': 'pjari',
        'TIMEOUT': 300,
    }
}

# Sessões em cache Redis (elimina query DB por request)
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

CELERY_BROKER_URL = _redis_url
CELERY_RESULT_BACKEND = _redis_url
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_RESULT_EXPIRES = 3600  # Resultados expiram em 1h — evita acúmulo no Redis
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Evita starvation na fila heavy (tasks de 600s)

from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'rodar-testes-jari-engine': {
        'task': 'chat.tasks.rodar_testes_engine_task',
        # A cada 6 horas (00h, 06h, 12h, 18h)
        'schedule': crontab(minute=0, hour='0,6,12,18'),
    },
    'predigerir-pacotes-normativos': {
        'task': 'chat.tasks.predigerir_pacotes_task',
        # 1x/dia às 03h (horário de baixo uso)
        'schedule': crontab(minute=0, hour=3),
    },
    # DESATIVADO: billing GCP desativado — Drive sync gera custo desnecessário
    # 'sync-normativo-drive': {
    #     'task': 'chat.tasks.sync_normativo_drive_task',
    #     'schedule': crontab(minute=0, hour='1,7,13,19'),
    # },
}

_LOG_HANDLERS_DJANGO = ['console'] if DEBUG else ['console', 'file']
_LOG_LEVEL_DJANGO    = 'WARNING'  if DEBUG else 'INFO'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'debug.log',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': _LOG_HANDLERS_DJANGO,
            'level': _LOG_LEVEL_DJANGO,
            'propagate': False,
        },
        'allauth': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'chat': {
            'handlers': _LOG_HANDLERS_DJANGO,
            'level': 'INFO',
            'propagate': False,
        },
        'pjari.perf': {
            'handlers': _LOG_HANDLERS_DJANGO,
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# TinyMCE Configuration
TINYMCE_DEFAULT_CONFIG = {
    'height': 500,
    'width': '100%',
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'selector': 'textarea',
    'theme': 'silver',
    'plugins': '''
            textcolor save link image media preview codesample contextmenu
            table code lists fullscreen  insertdatetime  nonbreaking
            contextmenu directionality searchreplace wordcount visualblocks
            visualchars code fullscreen autolink lists  charmap print  hr
            anchor pagebreak
            ''',
    'toolbar1': '''
            fullscreen preview bold italic underline | fontselect,
            fontsizeselect  | forecolor backcolor | alignleft alignright |
            aligncenter alignjustify | indent outdent | bullist numlist table |
            | link image media | codesample |
            ''',
    'toolbar2': '''
            visualblocks visualchars |
            charmap hr pagebreak nonbreaking anchor |  code |
            ''',
    'contextmenu': 'formats | link image',
    'menubar': True,
    'statusbar': True,
}
