"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-default-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

allowed_hosts = os.environ.get('ALLOWED_HOSTS')
if allowed_hosts:
    ALLOWED_HOSTS = allowed_hosts.split(',')
else:
    # Fallback for Railway if not explicitly set
    ALLOWED_HOSTS = ['*']

csrf_trusted = os.environ.get('CSRF_TRUSTED_ORIGINS')
if csrf_trusted:
    CSRF_TRUSTED_ORIGINS = csrf_trusted.split(',')
else:
    # Allow Railway and custom domains for CSRF by default
    CSRF_TRUSTED_ORIGINS = ['https://*.railway.app', 'https://pjarisc.com.br', 'https://www.pjarisc.com.br']

# Forçar uso do HTTPS para CSRF/Session em ambiente Prod (DEBUG=False)
if not DEBUG:
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Permitir sessão através do root e do www
    SESSION_COOKIE_DOMAIN = '.pjarisc.com.br'
    CSRF_COOKIE_DOMAIN = '.pjarisc.com.br'
    # Fix for social logins cross-origin validation
    SECURE_CROSS_ORIGIN_OPENER_POLICY = None
    
# Mercado Pago Settings
MERCADOPAGO_ACCESS_TOKEN = os.environ.get('MERCADOPAGO_ACCESS_TOKEN')
MERCADOPAGO_PUBLIC_KEY = os.environ.get('MERCADOPAGO_PUBLIC_KEY')
MERCADOPAGO_WEBHOOK_SECRET = os.environ.get('MERCADOPAGO_WEBHOOK_SECRET')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'anymail',
    'chat',
    
    # Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # Providers
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Allauth middleware
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# Allauth settings
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['first_name*', 'email*', 'password1*', 'password2*']
ACCOUNT_SIGNUP_FORM_CLASS = 'chat.adapters.CustomSignupForm'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
SOCIALACCOUNT_ADAPTER = 'chat.adapters.CustomSocialAccountAdapter'

if DEBUG:
    # Envio de e-mail para o terminal (Simulação de envio p/ Dev Local)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Envio real via Resend API (Produção)
    EMAIL_BACKEND = 'anymail.backends.resend.EmailBackend'
    ANYMAIL = {
        'RESEND_API_KEY': os.environ.get('RESEND_API_KEY', ''),
    }
    DEFAULT_FROM_EMAIL = 'validacao@pjarisc.com.br'
    SERVER_EMAIL = 'validacao@pjarisc.com.br'


# Pular a tela intermediária chata do allauth "sign in via..."
SOCIALACCOUNT_LOGIN_ON_GET = True

# Permitir logout com cliques simples em Links e Views cacheadas sem necessitar forms POST + CSRF ativo.
ACCOUNT_LOGOUT_ON_GET = True

# Permite conectar direto e não exige verificação dupla para quem loga com redes sociais
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"

# Optionally set login redirect to home
LOGIN_REDIRECT_URL = '/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        env='DATABASE_URL',
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Google Cloud Storage Configuration
USE_GCS = os.environ.get('USE_GCS', 'True') == 'True'

if USE_GCS:
    GS_BUCKET_NAME = os.environ.get('GS_BUCKET_NAME', 'pjari-midias')
    google_creds_env = os.environ.get('GOOGLE_APPLICATION_CREDENTIALS', '')
    
    # Se a variável de ambiente contiver o JSON inteiro em vez de um caminho de arquivo (como no Railway)
    if google_creds_env.strip().startswith('{'):
        import json
        from google.oauth2 import service_account
        
        try:
            creds_info = json.loads(google_creds_env)
            GS_CREDENTIALS = service_account.Credentials.from_service_account_info(creds_info)
            DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
            MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/'
            
            # Limpa a variável para evitar que o SDK padrão do Google tente usá-la como caminho de arquivo
            if 'GOOGLE_APPLICATION_CREDENTIALS' in os.environ:
                del os.environ['GOOGLE_APPLICATION_CREDENTIALS']
        except Exception as e:
            DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
            MEDIA_URL = '/media/'
            MEDIA_ROOT = BASE_DIR / 'media'
            
    else:
        # Modo fallback caso seja o nome do arquivo passando pelo SO (Local)
        GS_CREDENTIALS_FILE = google_creds_env or str(BASE_DIR / 'gcp-credentials.json')
        
        if os.path.exists(GS_CREDENTIALS_FILE):
            if 'GOOGLE_APPLICATION_CREDENTIALS' not in os.environ:
                os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = GS_CREDENTIALS_FILE
                
            DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
            MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/'
        else:
            # Fallback to local if credentials aren't found
            DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
            MEDIA_URL = '/media/'
            MEDIA_ROOT = BASE_DIR / 'media'
else:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'debug.log',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'allauth': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
